"""Run an example automatically."""
import pickle
import sys

import numpy as np

sys.path.append("src")
from search.state.reasoner_state import ReasonerState  # noqa:402
from datasets.reasoner_data_loader import get_state  # noqa:402
from search.policy.coherent_policy import priors_template, CoherentPolicy  # noqa:402
from llm.azure_open_ai_interface import run_azure_openai_prompts  # noqa:402

#####################
#
# METHANOL
#
#####################

# query = (
#     "Generate a list of top-5{ catalysts} that exhibit high activity for "
#     "the CO2 to methanol conversion reaction."
# )

# generation_answers = [
#     """1. Palladium (Pd): Palladium is a highly effective catalyst for the conversion of CO2 to methanol. The CO2 molecule adsorbs onto the Pd surface, and the bond between the carbon and oxygen atoms is weakened due to the interaction with the metallic catalyst. This facilitates the hydrogenation reaction, allowing methanol to be produced more easily.\n\n2. Copper (Cu): Copper-based catalysts are well-known for their effectiveness in methanol synthesis from CO2. The copper atoms provide active sites for CO2 activation, where the carbon-oxygen bonds in CO2 are weakened, promoting the reaction with hydrogen to form methanol.\n\n3. Ruthenium (Ru): Ruthenium is another metal that shows high catalytic activity for the CO2 to methanol conversion. The Ru atoms interact with the oxygen atoms in CO2, weakening the carbon-oxygen bonds and making it easier for the subsequent hydrogenation to occur.\n\n4. Platinum (Pt): Platinum is a popular choice for many catalytic processes, including the conversion of CO2 to methanol. The Pt surface provides active sites for the adsorption and activation of CO2, facilitating its reaction with hydrogen to form methanol.\n\n5. Nickel (Ni): Nickel has been found to be effective for CO2 conversion to methanol. The Ni atoms interact with the oxygen atoms in CO2, weakening the carbon-oxygen bonds and making it more susceptible to hydrogenation.\n\n```python\nfinal_answer = ['Palladium', 'Copper', 'Ruthenium', 'Platinum', 'Nickel']\n```""",
#     """Let's start by investigating the catalytic properties of the metals in the given list and then suggest alternatives for those with low hydrogenation capabilities. \n\n1. Palladium (Pd): Palladium is a well-known catalyst for hydrogenation reactions. However, in the context of CO2 to methanol conversion, it tends to favor the reverse water-gas shift reaction, leading to the formation of CO, not methanol. \n\n2. Copper (Cu): Copper-based catalysts, especially when combined with zinc oxide and alumina (Cu/ZnO/Al2O3), are the industrial standard for methanol synthesis from CO2 and H2. Copper exhibits good hydrogenation capability and selectivity towards methanol. \n\n3. Ruthenium (Ru): Ruthenium is a potent catalyst for hydrogenation reactions. However, it tends to favor the formation of methane from CO2, instead of methanol. \n\n4. Platinum (Pt): Platinum is a strong hydrogenation catalyst, but it predominantly drives CO2 towards methane and CO, not methanol.\n\n5. Nickel (Ni): Nickel is a robust catalyst for hydrogenation reactions, but it has a propensity for methanation (forming methane) rather than forming methanol.\n\nBased on the above analysis, we can infer that Palladium, Ruthenium, Platinum, and Nickel are not ideal for CO2 to methanol conversion due to their tendency to form products other than methanol. Copper, on the other hand, is a good candidate due to its high selectivity towards methanol.\n\nAs a result, we can propose replacements for the four metals with low selectivity towards methanol. The replacements are:\n\n1. Rhodium (Rh): Rhodium is a good hydrogenation catalyst and, when combined with certain promoters (like ZnO), can exhibit high selectivity for methanol formation from CO2.\n\n2. Iron (Fe): Iron, especially when promoted with K2O and Co, can catalyze the conversion of CO2 to methanol, thanks to its ability to facilitate hydrogenation and CO2 activation.\n\n3. Silver (Ag): Silver, though not a traditional hydrogenation catalyst, can facilitate the hydrogenation of CO2 to methanol when applied on suitable supports and under appropriate conditions.\n\n4. Gold (Au): Gold nanoparticles, particularly when supported on oxides like TiO2, have shown promise in converting CO2 to methanol, due to their ability to activate and hydrogenate CO2.\n\nSo, the final list of catalysts, which includes alternatives to those with low hydrogenation capabilities, would be:\n\n```python\nfinal_answer = ['Copper', 'Rhodium', 'Iron', 'Silver', 'Gold']\n```\nThese catalysts, under suitable conditions and in the right formulations, can facilitate the conversion of CO2 to methanol, a crucial reaction for sustainable fuel production and CO2 utilization.""",
#     """The initial list of catalysts you provided includes Copper, Rhodium, Iron, Silver, and Gold. However, some of these transition metals might not be the best choices for the CO2 to methanol conversion reaction due to their lower hydrogenation capability. Let's go through each of them:\n\n1. Copper: Copper (Cu) is often used in CO2 hydrogenation reactions, but its activity is typically enhanced when combined with other elements like Zinc due to its relatively low hydrogenation capability on its own.\n\n2. Rhodium: Rhodium (Rh) is a highly active metal for CO2 hydrogenation, but it often leads to over-hydrogenation, producing methane instead of methanol. \n\n3. Iron: Iron (Fe) is also used in CO2 hydrogenation reactions. However, its activity and selectivity toward methanol production are not as high as some other transition metals.\n\n4. Silver: Silver (Ag) is not typically used as a catalyst in hydrogenation reactions due to its relatively low activity.\n\n5. Gold: Gold (Au) has been found to be relatively inactive for CO2 hydrogenation reactions unless it is highly dispersed and/or supported on a suitable carrier.\n\nTherefore, considering the above-mentioned points, a more suitable list of transition metal catalysts for CO2 to methanol conversion might include:\n\n1. Palladium: Palladium (Pd) is highly active in hydrogenation reactions and can selectively catalyze the conversion of CO2 to methanol under certain conditions.\n\n2. Platinum: Platinum (Pt) has excellent hydrogenation capability and can be used to convert CO2 to methanol.\n\n3. Nickel: Nickel (Ni) is a relatively inexpensive and highly active catalyst for hydrogenation reactions, including CO2 to methanol conversion.\n\n4. Ruthenium: Ruthenium (Ru) is also an active and selective catalyst for the hydrogenation of CO2 to methanol.\n\n5. Copper-Zinc alloy: As mentioned earlier, Copper on its own has relatively low hydrogenation capability, but when alloyed with Zinc (Cu-Zn), it becomes a highly effective catalyst for the conversion of CO2 to methanol.\n\nHere is the python list you requested:\n\n```python\nfinal_answer = ['Palladium', 'Platinum', 'Nickel', 'Ruthenium', 'Copper-Zinc alloy']\n```""",
#     """After considering the properties of the suggested list of catalysts, I recommend the following transition metal alloy catalysts for the CO2 to methanol conversion reaction:\n\n1. **Palladium-Copper (Pd-Cu) alloy**: Palladium is known for its excellent hydrogenation ability. Coupling it with copper, which is an active catalyst for CO2 conversion, enhances the selectivity towards methanol production. The Pd-Cu alloy has been observed to exhibit a dual-function mechanism where palladium dissociates hydrogen into active hydrogen atoms, and copper activates CO2 and assembles the hydrogen atoms and CO2 into methanol.\n\n2. **Platinum-Tin (Pt-Sn) alloy**: Platinum is a robust catalyst with high hydrogenation capability. The addition of tin reduces the overpotential required for CO2 reduction and promotes the production of methanol by creating new active sites and facilitating the breaking of C-O bonds in CO2.\n\n3. **Nickel-Gallium (Ni-Ga) alloy**: Nickel, a well-known catalyst for hydrogenation, forms an alloy with gallium that shows high activity for CO2 hydrogenation to methanol. The Ni-Ga alloy demonstrates synergistic effects, where Ni aids the dissociation of hydrogen, and Ga facilitates the activation and conversion of CO2 to methanol.\n\n4. **Ruthenium-Copper (Ru-Cu) alloy**: Ruthenium is a highly active hydrogenation catalyst. When combined with copper, the resulting Ru-Cu alloy exhibits enhanced catalytic activity for CO2 to methanol conversion. The Ru sites in the alloy are responsible for hydrogen activation, while the Cu sites promote CO2 activation and the subsequent assembly of hydrogen and CO2 into methanol.\n\n5. **Copper-Palladium (Cu-Pd) alloy**: This alloy combines the strengths of both copper and palladium. Copper is a good catalyst for CO2 activation, while palladium is excellent for hydrogen dissociation. This alloy provides a dual function, enabling both the activation of CO2 and hydrogen and their subsequent assembly into methanol.\n\nHere is the python list named final_answer:\n\n```python\nfinal_answer = ['Palladium-Copper alloy', 'Platinum-Tin alloy', 'Nickel-Gallium alloy', 'Ruthenium-Copper alloy', 'Copper-Palladium alloy']\n```\nThese alloy catalysts should exhibit high activity for the CO2 to methanol conversion reaction, with improved hydrogenation capabilities compared to the initial list of catalysts.""",
#     """The CO2 to methanol conversion is a crucial reaction in renewable energy applications. This process involves the reduction of CO2 to methanol (CH3OH) and is typically facilitated by transition metal alloy catalysts. The desired catalysts should have a dual-function mechanism, meaning they can facilitate both the activation of CO2 and the subsequent hydrogenation process. Low hydrogenation capability is not desired.\n\n1. Copper-Zinc Alloy: The Cu-Zn alloy exhibits high activity for CO2 to methanol conversion due to its ability to activate CO2 and facilitate its hydrogenation to methanol. The Zinc in the alloy contributes to the activation of CO2 while the Copper facilitates the hydrogenation process.\n\n2. Copper-Gallium Alloy: The dual-function mechanism of the Cu-Ga alloy provides superior CO2 to methanol conversion performance. The Ga atoms weaken the C-O bonds in CO2, making it easier for the Copper atoms to facilitate the hydrogenation process.\n\n3. Palladium-Tin Alloy: The Pd-Sn alloy is known for its high CO2 to methanol conversion activity. Tin modifies the electronic structure of Palladium, which enhances the activation of CO2 and promotes the hydrogenation to methanol.\n\n4. Nickel-Zinc Alloy: The Ni-Zn alloy shows high activity for CO2 to methanol conversion. The Zinc in the alloy activates CO2 by weakening the C-O bonds, while Nickel facilitates the hydrogenation process.\n\n5. Platinum-Gallium Alloy: The Pt-Ga alloy has high activity for CO2 to methanol conversion. The Ga atoms help to activate CO2 by weakening the C-O bonds, and the Platinum atoms facilitate the hydrogenation process.\n\nNow I will return the final list as a python list:\n\nfinal_answer = ['Copper-Zinc alloy', 'Copper-Gallium alloy', 'Palladium-Tin alloy', 'Nickel-Zinc alloy', 'Platinum-Gallium alloy']""",
# ]
# priors_answers = [
#     """Based on the current search state, the root question, and the current answer, there are several possible actions we could take to refine the search. \n\n1) Change the type of catalyst to search for: Given that we have already explored metallic catalysts, we could consider looking into metallic alloy catalysts. Metallic alloys often have unique properties that differ from their individual components, potentially enhancing catalytic activity and selectivity.\n\n2) Add a new inclusion criteria: Based on the scientific explanations given in the current answer, we could include catalysts that have high adsorption capacity for CO2 and can weaken the carbon-oxygen bonds in CO2. This would make the hydrogenation process easier, thereby increasing the efficiency of the CO2 to methanol conversion process.\n\n3) Add a new exclusion criteria: We can exclude catalysts that have low hydrogenation capability. Since the hydrogenation of CO2 is a critical step in the conversion to methanol, catalysts with low hydrogenation capability would likely be less efficient in this reaction.\n\n4) Change the relationship to the candidate list: Currently, we are looking for catalysts that are \"similar to\" the ones in our candidate list. We could change this to \"different from\" to explore a broader range of catalysts, potentially discovering new ones that are highly effective for the CO2 to methanol conversion reaction.\n\nHere is the dictionary with the suggested actions:\n\n```python\n{\n \"catalyst_type\": [\"metallic alloy catalysts\"],\n \"inclusion_criteria\": [\"high adsorption capacity for CO2\", \"ability to weaken the carbon-oxygen bonds in CO2\"],\n \"exclusion_criteria\": [\"low hydrogenation capability\"],\n \"relationship_to_candidate_list\": [\"different from\"]\n}\n```""",
#     """Given the $current_answer, it is clear that the search for catalysts is focused on those that can facilitate the conversion of CO2 to methanol, with an exclusion criteria of low hydrogenation capability. The current list of catalysts in the $current_answer includes: 'Copper', 'Rhodium', 'Iron', 'Silver', 'Gold'. \n\n1. \"catalyst_type\": The current catalyst type is 'metallic catalysts'. While the current list of catalysts is relevant and effective, we could broaden the search to other types of metallic catalysts for variety. For example, we could look into 'transition metal catalysts' which includes a broader range of metals that are known for their catalytic activity.\n\n2. \"inclusion_criteria\": The current list does not have any inclusion criteria. Given the information from the $current_answer, we could include criteria such as 'high selectivity towards methanol' and 'ability to facilitate hydrogenation and CO2 activation'. These criteria are derived from the scientific explanations given for each of the catalysts in the $current_answer.\n\n3. \"exclusion_criteria\": The current exclusion criteria is 'low hydrogenation capability'. We can add to this by excluding catalysts that 'favor the formation of products other than methanol'. This is based on the explanations given for the catalysts Palladium, Ruthenium, Platinum, and Nickel, which were excluded from the final list in the $current_answer because they tend to form products other than methanol.\n\n4. \"relationship_to_candidate_list\": The current relationship to the candidate list is 'similar to'. Given that we have a new list of catalysts from the $current_answer, we could change this relationship to 'different from'. This would allow us to explore catalysts that are different from those already identified, providing a broader range of options.\n\nHere are the suggestions:\n\n```python\n{\n \"catalyst_type\": [\"transition metal catalysts\"],\n \"inclusion_criteria\": [\"high selectivity towards methanol\", \"ability to facilitate hydrogenation and CO2 activation\"],\n \"exclusion_criteria\": [\"favor the formation of products other than methanol\"],\n \"relationship_to_candidate_list\": [\"different from\"]\n}\n```""",
#     """Based on the $current_answer, the assistant suggests catalysts that have high hydrogenation capability and excludes those with low hydrogenation capability. It also introduces a new category of catalysts which are alloys. \n\nHere are my suggestions based on the guidelines:\n\n1) Catalyst Type: Since the assistant has already explored transition metal catalysts and found a number of effective options, we can dig deeper into a subclass of transition metal catalysts: 'transition metal alloy catalysts'. This is inspired by the mention of 'Copper-Zinc alloy' in the $current_answer.\n\n2) Inclusion Criteria: An additional inclusion criterion could be 'highly active and selective catalysts for the hydrogenation of CO2 to methanol'. The $current_answer has highlighted these properties as desirable in the given context.\n\n3) Exclusion Criteria: The assistant has already excluded catalysts with 'low hydrogenation capability'. We can add to this by also excluding catalysts that 'lead to over-hydrogenation, producing methane instead of methanol', as the $current_answer indicates that Rhodium, a transition metal, has this issue.\n\n4) Relationship to Candidate List: Since the current list of catalysts already includes a number of effective options, we could use the relationship 'includes alloys similar to the ones in the list'. The $current_answer includes the Copper-Zinc alloy, so this relationship would prompt the assistant to consider other transition metal alloys as well.\n\nHere is the dictionary of my suggestions:\n\n```python\n{\n \"catalyst_type\": [\"transition metal alloy catalysts\"],\n \"inclusion_criteria\": [\"highly active and selective catalysts for the hydrogenation of CO2 to methanol\"],\n \"exclusion_criteria\": [\"lead to over-hydrogenation, producing methane instead of methanol\"],\n \"relationship_to_candidate_list\": [\"includes alloys similar to the ones in the list\"]\n}\n```""",
#     """First, let's analyze the current state.\n\n- The current catalyst type is \"transition metal alloy catalysts\". \n- There are no inclusion criteria. \n- The exclusion criterion is \"low hydrogenation capability\".\n- The relationship to the candidate list is \"similar to\".\n\nNow, let's consider the root question and the current answer.\n\nThe root question is asking for a list of top-5 catalysts that exhibit high activity for the CO2 to methanol conversion reaction. The current answer successfully provides a list of transition metal alloy catalysts that have high hydrogenation capabilities, which is a key factor for high activity in the CO2 to methanol conversion reaction.\n\nGiven this, there seems to be no need to change the catalyst type, as the current type already fulfills the root question's requirement. However, we could potentially add new inclusion and exclusion criteria based on the scientific explanations provided in the current answer. Specifically, we could include catalysts that have dual-function mechanisms (i.e., they can activate both CO2 and hydrogen) and exclude catalysts that require a high overpotential for CO2 reduction. \n\nHere's the suggested action:\n\n```python\n{\n \"catalyst_type\": [],\n \"inclusion_criteria\": [\"dual-function mechanisms\"],\n \"exclusion_criteria\": [\"high overpotential for CO2 reduction\"],\n \"relationship_to_candidate_list\": []\n}\n```\n\nThis action would further refine the search for catalysts that are highly active for the CO2 to methanol conversion reaction. The inclusion criterion would ensure that the catalysts can effectively activate both CO2 and hydrogen, which is crucial for the reaction. The exclusion criterion would remove any catalysts that are energy-inefficient, as a high overpotential would require more energy to drive the reaction.""",
#     """Based on the current search state, the root prompt, and the current answer, we need to suggest possible actions to further refine our search for the top catalysts for the CO2 to methanol conversion reaction. The catalyst type should remain a transition metal alloy catalyst, as this is a broad category that can encompass a wide range of catalysts. The inclusion criterion is \"dual-function mechanisms\", which is highly relevant, as it ensures that the catalyst can both activate CO2 and facilitate the hydrogenation process. The exclusion criterion is \"low hydrogenation capability\", which is also relevant because a good catalyst for this reaction needs to efficiently hydrogenate CO2 to methanol.\n\nBased on the current answer, we know that the alloying element can play a significant role in enhancing the catalyst's ability to activate CO2 and facilitate the hydrogenation process. For example, in the Copper-Zinc alloy, Zinc contributes to the activation of CO2, while Copper facilitates the hydrogenation process.\n\nConsidering these facts, here are my suggestions:\n\n- \"catalyst_type\": [\"bimetallic alloy catalysts\", \"transition metal-carbon alloy catalysts\"]\n   We can narrow down the catalyst type to bimetallic alloy catalysts since all the examples given in the current answer are bimetallic. Another option could be transition metal-carbon alloy catalysts, considering that carbon could potentially contribute to the activation of CO2.\n\n- \"inclusion_criteria\": [\"high CO2 activation capability\", \"high hydrogenation rate\"]\n   We can specify the inclusion criteria further by mentioning the high CO2 activation capability and high hydrogenation rate, which are the two important aspects of the dual-function mechanism.\n\n- \"exclusion_criteria\": [\"low CO2 activation capability\", \"low methanol selectivity\"]\n   In addition to low hydrogenation capability, we can also exclude catalysts with low CO2 activation capability and low methanol selectivity, as these properties would reduce the catalyst's efficiency.\n\n- \"relationship_to_candidate_list\": [\"different from\", \"improved versions of\"]\n   We can change the relationship to the candidate list to \"different from\" or \"improved versions of\". This would allow us to explore catalysts that are not on the current list or those that are similar but have been further optimized.\n\nSo, the final dictionary would look like this:\n\n{\n \"catalyst_type\": [\"bimetallic alloy catalysts\", \"transition metal-carbon alloy catalysts\"],\n \"inclusion_criteria\": [\"high CO2 activation capability\", \"high hydrogenation rate\"],\n \"exclusion_criteria\": [\"low CO2 activation capability\", \"low methanol selectivity\"],\n \"relationship_to_candidate_list\": [\"different from\", \"improved versions of\"]\n}""",
# ]

# with open("methanol_trace.pkl", "rb") as f:
#     states = pickle.load(f)


# print(len(states))

# with open("methanol_trace.txt", "w") as f:
#     for s in states:
#         s.priors_template = priors_template
#         s.relation_to_candidate_list = (
#             s.relation_to_candidate_list
#             if s.relation_to_candidate_list is not None
#             else "similar to"
#         )
#         f.write(("*" * 30 + "\n") * 6)
#         f.write(s.generation_system_prompt)
#         f.write("\n" + ("-" * 30 + "\n") * 1)
#         f.write(s.generation_prompt)
#         f.write("\n" + ("=" * 30 + "\n") * 4)
#         if s.answer is not None:
#             f.write(s.answer)
#         else:
#             s.process_generation(generation_answers[len(states) - 1])
#         f.write(("-" * 30 + "\n") * 2)

#         f.write(s.priors_prompt)
#         if "priors" in s.info.keys():
#             print(s.info["priors"][-1]["answer"])
#         else:
#             s.process_prior(priors_answers[len(states) - 1])

# # next_state = s.return_next()
# # next_state.include_list.append("dual-function mechanisms")
# # states.append(next_state)

# print(len(states))
# with open("methanol_trace.pkl", "wb") as f:
#     pickle.dump(states, f)


#####################
#
# ETHANOL
#
#####################

query = (
    "Generate a list of top-5{ catalysts} that exhibit high activity for "
    "the CO2 to ethanol conversion reaction."
)

generation_answers = [
    """Sure, here are the top 5 metallic catalysts that exhibit high activity for the CO2 to ethanol conversion reaction:\n\n1. Copper (Cu): Copper is one of the most common catalysts used for CO2 reduction to ethanol. Copper has the ability to adsorb CO2 molecules on its surface and facilitate their conversion to ethanol. The adsorbed CO2 molecule is polarized, leading to the activation of the carbon-oxygen bond.\n\n2. Palladium (Pd): Palladium is also a good catalyst for this reaction. It can adsorb CO2 and hydrogen (H2) on its surface and facilitate their reaction to form ethanol. The presence of hydrogen helps to reduce the CO2 molecule, and palladium has active sites that can facilitate this reduction.\n\n3. Nickel (Ni): Nickel is a versatile catalyst that can catalyze a wide range of reactions, including the CO2 reduction to ethanol. Nickel has a high number of active sites that can adsorb CO2 and hydrogen. These adsorbed molecules can then react to form ethanol.\n\n4. Gold (Au): Gold can also catalyze the CO2 reduction to ethanol. Gold nanoparticles can adsorb CO2 and hydrogen and facilitate their reaction to form ethanol. The high surface area of gold nanoparticles provides many active sites for the reaction.\n\n5. Platinum (Pt): Platinum is a highly efficient catalyst for the CO2 reduction to ethanol. Platinum has a high number of active sites that can adsorb CO2 and hydrogen. These adsorbed molecules can then react to form ethanol.\n\nHere's the python list you requested:\n\n```python\nfinal_answer = ['Copper (Cu)', 'Palladium (Pd)', 'Nickel (Ni)', 'Gold (Au)', 'Platinum (Pt)']\n```""",
    """The desired catalytic reaction, the conversion of CO2 to ethanol, is a complex multi-step process. It involves the initial activation of CO2, followed by the reduction steps to transform CO2 into ethanol. The overall reaction can be described as follows: CO2 + 6H+ + 6e- -> C2H5OH + H2O.\n\nHere are my top recommendations for alloy catalysts that might exhibit high activity for this reaction, along with some scientific justifications:\n\n1. **Copper-Zinc (Cu-Zn) Alloy**: Copper is known for its ability to facilitate the reduction of CO2, while zinc can help to improve the selectivity towards ethanol production. The synergistic effect between copper and zinc could enhance both the activity and selectivity of the catalyst.\n\n2. **Copper-Gold (Cu-Au) Alloy**: Gold can improve the stability of copper, which tends to agglomerate under CO2 reduction conditions. Moreover, the electronic interaction between copper and gold might create more active sites for CO2 reduction.\n\n3. **Copper-Palladium (Cu-Pd) Alloy**: Palladium can improve the hydrogenation ability of the catalyst, which is beneficial for the final steps of the CO2 to ethanol conversion. The alloying of copper with palladium could enhance the overall catalytic performance.\n\n4. **Nickel-Gold (Ni-Au) Alloy**: Nickel is a good catalyst for CO2 reduction, but it often suffers from poor selectivity. Gold can help to improve the selectivity towards ethanol production. The combination of nickel and gold could yield a highly active and selective catalyst.\n\n5. **Platinum-Gold (Pt-Au) Alloy**: Platinum is an excellent catalyst for hydrogenation reactions, while gold can improve the stability and selectivity of the catalyst. The alloying of platinum with gold could provide a high-performing catalyst for the CO2 to ethanol conversion.\n\nIn comparison to the original list of single metal catalysts, these alloy catalysts are expected to offer improved performance due to the synergistic effects between the two metals in each alloy.\n\nThe final Python list would be as follows:\n\n```python\nfinal_answer = ['Copper-Zinc (Cu-Zn) Alloy', 'Copper-Gold (Cu-Au) Alloy', 'Copper-Palladium (Cu-Pd) Alloy', 'Nickel-Gold (Ni-Au) Alloy', 'Platinum-Gold (Pt-Au) Alloy']\n```""",
    """Certainly, let's examine each of these catalysts and identify alternatives that could potentially exhibit higher activity for the CO2 to ethanol conversion reaction.\n\n1. **Copper-Iron (Cu-Fe) Alloy**: The synergy between copper and iron in a Cu-Fe alloy catalyst can enhance the catalytic activity for CO2 to ethanol conversion. Copper can adsorb CO2 and facilitate its reduction, while iron can effectively dissociate water molecules to provide necessary protons and electrons for the reduction process.\n\n2. **Copper-Silver (Cu-Ag) Alloy**: Silver can help to reduce the overpotential of the reaction and improve the selectivity towards ethanol production. The Cu-Ag alloy can bind CO2 at an optimal strength, which is neither too strong to inhibit its reduction, nor too weak to lose it before the reduction.\n\n3. **Copper-Nickel (Cu-Ni) Alloy**: The Cu-Ni alloy shows a synergistic effect where copper aids in CO2 adsorption and reduction, while nickel promotes the C-C coupling, improving the selectivity towards ethanol.\n\n4. **Nickel-Iron (Ni-Fe) Alloy**: This alloy also exhibits a synergistic effect. Nickel can adsorb CO2 and facilitate its reduction, while iron can effectively dissociate water molecules to provide necessary protons and electrons for the reduction process.\n\n5. **Palladium-Gold (Pd-Au) Alloy**: Gold can stabilize the Pd catalyst and enhance its resistance to poisoning and sintering. The synergistic effect of Pd-Au can reduce the overpotential of the reaction and improve the selectivity towards ethanol.\n\nComparing these to the initial list, we notice that we are recommending different alloys. The idea is that by introducing other metals, we can enhance the properties of the catalyst, such as adsorption capacity, reduction potential, and selectivity towards ethanol.\n\nFinally, we can put these catalysts into a python list named final_answer:\n\n```python\nfinal_answer = ['Copper-Iron (Cu-Fe) Alloy', 'Copper-Silver (Cu-Ag) Alloy', 'Copper-Nickel (Cu-Ni) Alloy', 'Nickel-Iron (Ni-Fe) Alloy', 'Palladium-Gold (Pd-Au) Alloy']\n```""",
    """Sure, let's evaluate the given list and propose a new one based on the criteria given. \n\n1. Copper-Iron (Cu-Fe) Alloy: This alloy shows a good activity for CO2 to ethanol conversion due to the synergistic effect between the two metals. Copper is known for its CO2 reduction ability, while iron enhances this property. However, Cu-Fe alloy tends to bind CO2 too strongly, which might hinder the reaction kinetics.\n\n2. Copper-Silver (Cu-Ag) Alloy: This alloy also shows a synergistic effect, where silver aids the selective conversion of CO2 to ethanol by copper. However, the binding of CO2 to this alloy might be too weak, affecting the reaction efficiency.\n\n3. Copper-Nickel (Cu-Ni) Alloy: This alloy is known for its catalytic activity in CO2 reduction. The synergistic effect between copper and nickel enhances the CO2 to ethanol conversion. The binding strength of CO2 to this alloy is also favorable, making it a suitable candidate.\n\n4. Nickel-Iron (Ni-Fe) Alloy: Although this alloy shows some activity in CO2 reduction, it's not specifically known for its ability to convert CO2 to ethanol. The binding of CO2 to this alloy might not be optimal.\n\n5. Palladium-Gold (Pd-Au) Alloy: This alloy is not traditionally used in CO2 to ethanol conversion. Palladium and gold are more commonly used in other types of catalytic reactions. The binding of CO2 to this alloy might be too weak.\n\nBased on the given properties and the evaluation of the given list, I would recommend the following top-5 alloy catalysts for the CO2 to ethanol conversion:\n\n1. Copper-Nickel (Cu-Ni) Alloy: As mentioned earlier, this alloy shows a good synergistic effect and optimal binding of CO2.\n\n2. Copper-Zinc (Cu-Zn) Alloy: This alloy is known for its high activity in CO2 to ethanol conversion. Zinc enhances the reduction ability of copper and the alloy binds CO2 optimally.\n\n3. Copper-Tin (Cu-Sn) Alloy: Tin enhances the CO2 reduction ability of copper. The binding strength of CO2 to this alloy is also favorable.\n\n4. Copper-Indium (Cu-In) Alloy: Indium aids in the selective conversion of CO2 to ethanol, and this alloy has optimal CO2 binding strength.\n\n5. Copper-Gallium (Cu-Ga) Alloy: Gallium enhances the CO2 reduction ability of copper, and the alloy binds CO2 optimally.\n\n```python\nfinal_answer = ['Copper-Nickel (Cu-Ni) Alloy', 'Copper-Zinc (Cu-Zn) Alloy', 'Copper-Tin (Cu-Sn) Alloy', 'Copper-Indium (Cu-In) Alloy', 'Copper-Gallium (Cu-Ga) Alloy']\n```""",
    """1. Palladium-Copper (Pd-Cu) Alloy: This alloy shows a synergistic effect where copper helps in the activation of CO2 while palladium aids in the hydrogenation process. The CO2 molecule is adsorbed onto the copper site and is subsequently activated by the transfer of charge from copper to CO2, resulting in a bent CO2 configuration. The hydrogenation of activated CO2 is facilitated by palladium, leading to ethanol production.\n\n2. Palladium-Nickel (Pd-Ni) Alloy: Nickel promotes the adsorption and dissociation of CO2, while palladium catalyzes the hydrogenation of adsorbed CO2. Nickel donates electrons to the anti-bonding orbital of CO2, which weakens the C=O bond and facilitates the dissociation of CO2. The adsorbed CO2 then undergoes hydrogenation at the palladium sites, leading to the formation of ethanol.\n\n3. Palladium-Zinc (Pd-Zn) Alloy: Zinc serves as an electronic modifier and promotes the adsorption of CO2 by donating electrons to the anti-bonding orbital of CO2, thus weakening the C=O bond. Palladium then catalyzes the hydrogenation of the adsorbed CO2.\n\n4. Palladium-Tin (Pd-Sn) Alloy: Tin alters the electronic properties of palladium in a way that enhances CO2 adsorption and activation. The charge transfer from tin to CO2 results in a bent CO2 configuration, which is more susceptible to hydrogenation. Palladium then catalyzes the hydrogenation of the activated CO2.\n\n5. Palladium-Indium (Pd-In) Alloy: Indium promotes the activation of CO2 by donating electrons to the anti-bonding orbital of CO2, thus facilitating the adsorption and activation of CO2. Palladium then catalyzes the hydrogenation of the activated CO2.\n\nFinal Python list:\n\n```python\nfinal_answer = ['Palladium-Copper (Pd-Cu) Alloy', 'Palladium-Nickel (Pd-Ni) Alloy', 'Palladium-Zinc (Pd-Zn) Alloy', 'Palladium-Tin (Pd-Sn) Alloy', 'Palladium-Indium (Pd-In) Alloy']\n```""",
]
priors_answers = [
    """The $current_answer provided a list of metallic catalysts that exhibit high activity for the CO2 to ethanol conversion reaction, along with scientific explanations for each catalyst's efficiency. The catalysts include Copper, Palladium, Nickel, Gold, and Platinum. The explanations mention properties such as ability to adsorb CO2 and hydrogen molecules, the presence of active sites that facilitate the reduction of CO2, and the polarization of the adsorbed CO2 molecule leading to the activation of the carbon-oxygen bond.\n\nThe $root_prompt asks to generate a list of top-5 catalysts, and it doesn't specify that the catalysts should be metallic. However, our $current_prompt specifies the type of catalyst as metallic. Thus, there is room for exploring other types of catalysts.\n\nHere are my suggestions:\n\n- We could change the \"catalyst_type\" to include \"alloy catalysts.\" Alloy catalysts are made by combining two or more metallic elements, which can result in improved catalytic properties. For instance, Cu-Pd alloy has been reported to show enhanced activity for CO2 to ethanol conversion due to the synergistic effect of copper and palladium.\n\n- We could add an \"inclusion_criteria\" that the catalysts must be able to facilitate the reaction in a wide range of conditions, such as varying temperature and pressure. This is important for practical applications.\n\n- We could add an \"exclusion_criteria\" that the catalysts should not be expensive or rare, as this could limit their widespread use. For instance, although platinum is a highly efficient catalyst, its high cost and scarcity could be a disadvantage.\n\n- We could \"change the relationship to the candidate list\" to be \"complementary to.\" This would allow us to consider catalysts that may not be as high-activity as the ones already listed, but could still play a significant role in the CO2 to ethanol conversion reaction when used together with the top-performing catalysts.\n\nHere's the dictionary mapping:\n\n{\n    \"catalyst_type\": [\"alloy catalysts\"],\n    \"inclusion_criteria\": [\"able to facilitate the reaction in a wide range of conditions\"],\n    \"exclusion_criteria\": [\"should not be expensive or rare\"],\n    \"relationship_to_candidate_list\": [\"complementary to\"]\n}""",
    """Given the current state, there are several possible actions we could take. Let's consider each possible action in the action space.\n\n1. **Change the type of catalyst to search for**: Currently, we are looking for alloy catalysts. As we can see from the current answer, alloy catalysts have been suggested that combine the beneficial properties of different metals to improve the catalytic activity and selectivity. This seems to be a logical approach, as alloy catalysts can offer synergistic effects. One possible change could be to look for \"bimetallic catalysts\", which is a subclass of alloy catalysts. This would be in line with the current search state and the explanations given in the current answer.\n\n2. **Add a new inclusion criteria**: The current inclusion criteria is an empty list. Based on the current answer, one possible inclusion criteria could be \"catalysts that show a synergistic effect between two metals\". This is based on the scientific explanations given in the current answer, which highlight the importance of synergistic effects in improving the performance of the catalysts.\n\n3. **Add a new exclusion criteria**: Currently, the exclusion criteria is an empty list. Given the guidelines, one possible exclusion criteria could be \"catalysts that include MOFs, Zeolites, or non-metals\", as these categories should not be considered.\n\n4. **Change the relationship to the candidate list**: The current relationship to the candidate list is \"similar to\". Given that we are looking for catalysts that may exhibit improved performance due to the synergistic effects between two metals, a possible change could be to look for catalysts that are \"different from\" the ones in the candidate list, as we are looking for catalysts that combine two metals, not single metal catalysts.\n\nHere is the dictionary mapping of the suggestions:\n\n```python\n{\n \"catalyst_type\": [\"bimetallic catalysts\"],\n \"inclusion_criteria\": [\"catalysts that show a synergistic effect between two metals\"],\n \"exclusion_criteria\": [\"catalysts that include MOFs, Zeolites, or non-metals\"],\n \"relationship_to_candidate_list\": [\"different from\"]\n}\n```""",
    """Based on the current catalyst list and explanations provided, it's clear that a synergistic effect between two metals in alloy catalysts is beneficial for the CO2 to ethanol conversion reaction. We see that certain metals play specific roles in enhancing the reaction such as copper aiding in CO2 adsorption and reduction, silver and gold reducing the overpotential of the reaction and improving selectivity towards ethanol, and iron aiding in the dissociation of water molecules.\n\nGiven this, I suggest the following possible actions:\n\n1) Change the type of catalyst to search for: We could look for \"intermetallic compounds\" which are a type of alloy where the metals are ordered in a specific arrangement. This could potentially enhance the synergistic effect between the metals.\n\n2) Add a new inclusion criteria: We could add \"catalysts that show improved resistance to poisoning and sintering\", as this was mentioned as a beneficial property in the Palladium-Gold (Pd-Au) Alloy explanation. \n\n3) Add a new exclusion criteria: We could exclude \"catalysts that bind CO2 too strongly or too weakly\", since an optimal CO2 binding strength was mentioned as important in the Copper-Silver (Cu-Ag) Alloy explanation.\n\n4) Change the relationship to the candidate list: We could change the relationship to \"enhanced properties compared to\" the candidate list. This would mean we are looking for catalysts that have the same beneficial properties as those in the candidate list but perform even better.\n\nHere is the final dictionary:\n\n```\n{\n  \"catalyst_type\": [\"intermetallic compounds\"],\n  \"inclusion_criteria\": [\"catalysts that show improved resistance to poisoning and sintering\"],\n  \"exclusion_criteria\": [\"catalysts that bind CO2 too strongly or too weakly\"],\n  \"relationship_to_candidate_list\": [\"enhanced properties compared to\"]\n}\n```""",
    """Based on the current state, prompt, question, and answer, here are my suggestions:\n\n1) Change the type of catalyst to search for: The current alloy catalysts are primarily based on copper. This makes sense because copper is a metal that's known for its ability to reduce CO2. However, we could also look into other metals with similar properties to copper. For instance, we could look into \"Palladium-based alloy catalysts\". Palladium is a metal with high catalytic activity, and its alloys might show a synergistic effect with other metals, leading to enhanced activity for CO2 to ethanol conversion.\n\n2) Add a new inclusion criteria: Based on the current answer, it seems like a crucial factor for high activity in CO2 to ethanol conversion is the synergistic effect between two metals. Therefore, we could add a new criterion that specifies the nature of this effect. For instance, we could add \"alloys where one metal enhances the reduction ability of the other\".\n\n3) Add a new exclusion criteria: From the current answer, it appears that the binding strength of CO2 to the catalyst plays a significant role in the efficiency of the reaction. Thus, we could specify this property further by adding \"catalysts that do not show optimal CO2 binding strength as determined by computational chemistry calculations\".\n\n4) Change the relationship to the candidate list: The current relationship is \"similar to\", which means we are looking for catalysts that are like those in the given list. However, we might want to expand our search to catalysts that are \"better than\" those in the list. This might include catalysts that meet all the inclusion criteria, none of the exclusion criteria, and demonstrate higher activity for the CO2 to ethanol conversion.\n\nHere is the dictionary with my suggestions:\n\n```python\n{\n \"catalyst_type\": [\"Palladium-based alloy catalysts\"],\n \"inclusion_criteria\": [\"alloys where one metal enhances the reduction ability of the other\"],\n \"exclusion_criteria\": [\"catalysts that do not show optimal CO2 binding strength as determined by computational chemistry calculations\"],\n \"relationship_to_candidate_list\": [\"better than\"]\n}\n```""",
    """The current $search_state is focused on \"palladium-based alloy catalysts\" that \"show a synergistic effect between two metals\" and do not \"bind CO2 too strongly or too weakly\". The catalysts in the $current_answer seem to fit these criteria well, as they are palladium-based alloys and their descriptions highlight the synergistic effects between palladium and the other metal in the alloy. \n\nHowever, the $root_prompt asks for a list of top-5 catalysts, not necessarily limited to palladium-based ones, that exhibit high activity for the CO2 to ethanol conversion reaction. Therefore, we could consider expanding the search beyond palladium-based alloy catalysts, while still adhering to the inclusion and exclusion criteria. \n\nAs for the inclusion criteria, it could be beneficial to look for catalysts that also possess a high surface area or high porosity, as this could potentially increase the number of active sites available for the reaction, thus enhancing the catalyst's activity. \n\nRegarding the exclusion criteria, we can add catalysts that are sensitive to poisoning or deactivation as these would not be ideal for long-term or industrial use. \n\nFinally, we can consider catalysts that are \"different from\" the initial candidate list, since the $root_prompt does not explicitly require the final list to be similar to the initial candidate list.\n\nHere are some suggestions based on the above considerations:\n\n```python\nsuggested_actions = {\n  \"catalyst_type\": [\"nickel-based alloy catalysts\", \"copper-based alloy catalysts\"],\n  \"inclusion_criteria\": [\"catalysts that show a synergistic effect between two metals\", \"catalysts with high surface area or high porosity\"],\n  \"exclusion_criteria\": [\"catalysts that bind CO2 too strongly or too weakly\", \"catalysts that are sensitive to poisoning or deactivation\"],\n  \"relationship_to_candidate_list\": [\"different from\"]\n}\n```\nThese suggestions expand the search to include other types of catalysts that could potentially exhibit high activity for the CO2 to ethanol conversion reaction. The inclusion of high surface area or high porosity in the inclusion criteria could potentially increase the number of active sites available for the reaction, thus enhancing the catalyst's activity. The addition of catalysts that are sensitive to poisoning or deactivation to the exclusion criteria ensures that the final list of catalysts is suitable for long-term or industrial use.""",
]


s = get_state("CO2ToEthanol", query, chain_of_thought=True)
states = [s]

s.catalyst_label = " metallic catalysts"
s.priors_template = priors_template
s.relation_to_candidate_list = (
    s.relation_to_candidate_list
    if s.relation_to_candidate_list is not None
    else "similar to"
)
policy = CoherentPolicy(llm_function=run_azure_openai_prompts)
for i in range(5):
    s = states[i]
    print(len(states))
    print(("*" * 30 + "\n") * 6)
    print(s.generation_system_prompt)
    print("\n" + ("-" * 30 + "\n") * 1)
    print(s.generation_prompt)
    print("\n" + ("=" * 30 + "\n") * 4)

    answer = run_azure_openai_prompts(
        [s.generation_prompt], [s.generation_system_prompt]
    )
    s.process_generation(answer[0])
    print(("-" * 30 + "\n") * 2)
    action_priors = policy.get_actions([s])
    actions, priors = action_priors[0]
    possible_idx = np.argwhere(priors != 0)[:, 0]
    action_idx = possible_idx[np.random.randint(len(possible_idx))]
    action = actions[action_idx]

    states.append(action(s))
states.pop()

with open("ethanol_automatic_trace.pkl", "wb") as f:
    pickle.dump(states, f)


with open("ethanol_automatic_trace.txt", "w") as f:
    for i, s in enumerate(states):
        f.write(("*" * 30 + "\n") * 6)
        f.write(s.generation_system_prompt)
        f.write("\n" + ("-" * 30 + "\n") * 1)
        f.write(s.generation_prompt)
        f.write("\n" + ("=" * 30 + "\n") * 4)
        f.write(s.answer)
        f.write(("-" * 30 + "\n") * 2)

        f.write(s.priors_prompt)

        f.write(s.info["priors"][-1]["answer"])
